version: '3.8'
services:
  db:
    image: postgres:16
    container_name: ums_db
    environment:
      POSTGRES_USER: ums
      POSTGRES_PASSWORD: ums
      POSTGRES_DB: wms
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: