spring:
  application:
    name: wms
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:wms}?currentSchema=${DB_SCHEMA:ums}
    username: ${DB_USERNAME:wms}
    password: ${DB_PASSWORD:wms}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${DB_SCHEMA:ums}
  sql:
    init:
      mode: never
server:
  port: 8080

app:
  jwt:
    secret: "change-me-very-long-random-secret"
    expiration-minutes: 60
  auth:
    cookie:
      name: "AUTH_TOKEN"
      domain: ""
      path: "/"
      secure: false
      httpOnly: true
      sameSite: "Lax"
