spring:
  application:
    name: wms
  datasource:
    url: jdbc:postgresql://localhost:5432/wms?currentSchema=ums
    username: wms
    password: wms
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ums
  sql:
    init:
      mode: never
server:
  port: 8080

app:
  jwt:
    secret: "change-me-very-long-random-secret"
    expiration-minutes: 1440
  auth:
    cookie:
      name: "AUTH_TOKEN"
      domain: ""
      path: "/"
      secure: false
      httpOnly: true
      sameSite: "Lax"
